- name: Apply rhcos-hosts plan
  terraform:
    project_path: "{{ role_path }}/files"
    backend_config:
      path: "{{ role_path }}/../../.state/rhcos-hosts/{{ cluster_id }}/terraform.tfstate"
    force_init: true
    variables:
      vcenter_api_user: "{{ vcenter_api_user }}"
      vcenter_api_password: "{{ vcenter_api_password }}"
      vcenter_storage_user: "{{ vcenter_storage_user }}"
      vcenter_server_name: "{{ vcenter_server_name }}"
      vcenter_datacenter_name: "{{ vcenter_datacenter_name }}"
      vcenter_cluster_name: "{{ vcenter_cluster_name }}"
      vcenter_datastore_name: "{{ vcenter_datastore_name }}"
      vcenter_network_name: "{{ vcenter_network_name }}"
      vcenter_folder_path: "{{ vcenter_folder_path }}"
      rhcos_template_name: "{{ rhcos_template_name }}"
      cluster_id: "{{ cluster_id }}"
      bootstrap_cpus: "{{ bootstrap_cpus }}"
      bootstrap_memory: "{{ bootstrap_memory }}"
      bootstrap_disk: "{{ bootstrap_disk }}"
      bootstrap_ignition_url: "{{ bootstrap_ignition_url }}"
      bootstrap_vm_mac: "{{ bootstrap_vm_mac }}"
      master_cpus: "{{ master_cpus }}"
      master_memory: "{{ master_memory }}"
      master_disk: "{{ master_disk }}"
      master_ignition_path: "{{ master_ignition_path }}"
      master_vm_mac_list: "{{ master_vm_mac_list }}"
      worker_cpus: "{{ worker_cpus }}"
      worker_memory: "{{ worker_memory }}"
      worker_disk: "{{ worker_disk }}"
      worker_ignition_path: "{{ worker_ignition_path }}"
      worker_vm_count: "{{ worker_vm_count }}"
      worker_vm_mac_list: "{{ worker_vm_mac_list }}"
