- name: Install prerequisite yum packages
  yum:
    name: "{{ item }}"
  loop:
  - python-pip # for pip module

- name: Install prerequisite python packages
  pip:
    name: "{{ item }}"
  loop:
  - dnspython # for dig lookup module